Add trivy scan to docker images of quick deployable samples (#170)

diff --git a/.azure/build.yaml b/.azure/build.yaml
--- a/.azure/build.yaml
+++ b/.azure/build.yaml
@@ -36,6 +36,43 @@ steps:
   - script: python .azure/scripts/process_metadata.py 
     displayName: 'Run metadata extraction script'
 
+  - script: |
+      echo "Giving execute permission to trivy-scan.sh"
+      chmod +x .azure/scripts/trivy-scan.sh
+    displayName: "Set execute permissions"
+
+  - template: install/install-trivy.yaml@common-templates
+  - script: |
+        echo "##[group]Running Trivy scan for each image"
+
+        exit_code=0
+
+        while read -r image; do
+          echo "Scanning image: $image"
+          .azure/scripts/trivy-scan.sh "$image"
+
+          scan_exit_code=$?
+
+          if [ $scan_exit_code -ne 0 ]; then
+            echo "Trivy scan failed for image: $image"
+            exit_code=1  # Mark exit_code as failure
+          fi
+        done < image_urls.txt
+
+        echo "##[endgroup]"
+
+        exit $exit_code
+    displayName: "Run Trivy scan for quick deployable images"
+
+  - script: |
+        echo "##[group]Pushing images to ACR"
+        while read -r image; do
+          echo "Pushing image: $image"
+          docker push "$image"
+        done < image_urls.txt
+        echo "##[endgroup]"
+    displayName: 'Push Quick Deployable Docker Images'
+
   - task: AzureCLI@2
     displayName: Upload files to Azure Storage Account
     inputs:
diff --git a/.azure/pr-check.yaml b/.azure/pr-check.yaml
--- a/.azure/pr-check.yaml
+++ b/.azure/pr-check.yaml
@@ -1,3 +1,10 @@
+resources:
+  repositories:
+    - repository: common-templates
+      type: github
+      name: wso2-enterprise/choreo-common-pipeline-templates
+      endpoint: wso2-enterprise
+
 trigger: none
 
 pr:
@@ -22,6 +29,33 @@ steps:
   - script: |
       python .azure/scripts/validate_samples.py
     displayName: "Metadata Validation"
+
+  - script: |
+      echo "Giving execute permission to trivy-scan.sh"
+      chmod +x .azure/scripts/trivy-scan.sh
+    displayName: "Set execute permissions"
+
+  - template: install/install-trivy.yaml@common-templates
+  - script: |
+        echo "##[group]Running Trivy scan for each image"
+
+        exit_code=0
+
+        while read -r image; do
+          echo "Scanning image: $image"
+          .azure/scripts/trivy-scan.sh "$image"
+
+          scan_exit_code=$?
+
+          if [ $scan_exit_code -ne 0 ]; then
+            echo "Trivy scan failed for image: $image"
+            exit_code=1  # Mark exit_code as failure
+          fi
+        done < image_urls.txt
+
+        echo "##[endgroup]"
+        exit $exit_code
+    displayName: "Run Trivy scan for quick deployable images"
 
   - script: echo 'Pull Request Validation Completed'
     displayName: "PR Validation Completed"
