Fix

diff --git a/.azure/pr-check.yaml b/.azure/pr-check.yaml
--- a/.azure/pr-check.yaml
+++ b/.azure/pr-check.yaml
@@ -30,10 +30,14 @@ steps:
       python .azure/scripts/validate_samples.py
     displayName: "Metadata Validation"
 
-  # Read the image_urls.txt file and set it as a variable
   - script: |
-      IMAGE_URLS=$(cat $(BUILD_SOURCESDIRECTORY)/image_urls.txt)
-      echo "##vso[task.setvariable variable=IMAGE_URLS]$IMAGE_URLS"
+      if [ -f "$(BUILD_SOURCESDIRECTORY)/image_urls.txt" ]; then
+        IMAGE_URLS=$(cat "$(BUILD_SOURCESDIRECTORY)/image_urls.txt")
+        echo "##vso[task.setvariable variable=IMAGE_URLS]$IMAGE_URLS"
+      else
+        echo "File not found: $(BUILD_SOURCESDIRECTORY)/image_urls.txt"
+        exit 1
+      fi
     displayName: "Read image_urls.txt"
 
   - template: install/install-trivy.yaml@common-templates
